import {readFileSync} from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const html=readFileSync('dist/ar.html','utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const code=script.slice(script.indexOf('function cameraMessage('),script.indexOf('async function listCameras('));
function harness({failure,fallback,secure=true,playFailure=false,delayed=false}={}){let calls=0,stopped=0,resolve;const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',disabled:false,classList:{add(){},remove(){},toggle(){}}});return elements.get(id)};const track={stop(){stopped++},getSettings(){return {facingMode:'environment'}},label:'rear',addEventListener(){},getCapabilities(){return {}}},stream={getTracks:()=>[track],getVideoTracks:()=>[track]};const c={token:0,stream:null,track:null,busy:false,res:1280,devIdx:-1,deviceIds:[{id:'rear'}],facing:'environment'};const video={srcObject:null,classList:{toggle(){}},async play(){if(playFailure)throw Object.assign(new Error('play blocked'),{name:'NotAllowedError'})}};const ctx=vm.createContext({C:c,video,document:{hidden:false},window:{isSecureContext:secure},navigator:{mediaDevices:{async getUserMedia(){calls++;if(delayed)return new Promise(r=>resolve=r);if(failure)throw Object.assign(new Error('denied'),{name:failure});if(fallback&&calls===1)throw Object.assign(new Error('constraint'),{name:'OverconstrainedError'});return stream}}},$:element,prevLuma:null,applyTorch(){},applyExposure(){},listCameras(){},camErr:e=>e.message});vm.runInContext(code,ctx);return {ctx,c,element,stream,counts:()=>({calls,stopped}),resolve:()=>resolve(stream)}}
let h=harness();await h.ctx.startCamera();assert.equal(h.c.stream,h.stream);assert.equal(h.c.busy,false);
h.ctx.stopCamera();assert.equal(h.counts().stopped,1);assert.equal(h.ctx.video.srcObject,null);
h=harness({failure:'NotAllowedError'});await h.ctx.startCamera();assert.equal(h.counts().calls,1);assert.equal(h.c.stream,null);assert(h.element('cameraHelpText').textContent.includes('denied'));
h=harness({fallback:true});await h.ctx.startCamera();assert.equal(h.counts().calls,2);assert.equal(h.c.stream,h.stream);
h=harness({secure:false});await h.ctx.startCamera();assert.equal(h.counts().calls,0);assert(h.element('cameraHelpText').textContent.includes('HTTPS'));
h=harness({playFailure:true});await h.ctx.startCamera();assert.equal(h.counts().stopped,1);assert.equal(h.c.stream,null);
h=harness({delayed:true});const pending=h.ctx.startCamera();h.ctx.document.hidden=true;h.resolve();await pending;assert.equal(h.counts().stopped,1);assert.equal(h.c.stream,null);
assert(html.includes('AR SIMULATION · FICTIONAL OVERLAY'));assert(!html.includes("+ ' mG'"));console.log('PASS: camera start, stop, denied permission, constraint fallback, HTTPS guard, play failure cleanup, background cancellation, simulation labeling');
