import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const html=readFileSync('dist/ar.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const modeCode=script.slice(script.indexOf('const runMode ='),script.indexOf('function setMeasure('));const ctx=vm.createContext({DEMO:{on:false},ui:{measure:false}});vm.runInContext(modeCode+'globalThis.mode=runMode;globalThis.label=captureLabel',ctx);assert.equal(ctx.mode(),'ar_simulation_with_live_sensors');ctx.ui.measure=true;assert.equal(ctx.mode(),'measure');assert.equal(ctx.label(),'MEASUREMENT · SENSOR DATA');ctx.DEMO.on=true;assert.equal(ctx.mode(),'all_simulated');assert.equal(ctx.label(),'DEMO · SIMULATED DATA');
// CSV should contain actual channels or null, and no fictional values in measurement mode.
const loggerCode=script.slice(script.indexOf('const L = {'),script.indexOf('// ---------------------------------------------------------------- sessions'));
const data=vm.createContext({performance:{now:()=>1000},MAG:{live:false,anomaly:false,baseline:null},DEMO:{on:false},ui:{measure:true},S:{hasAcc:false,hasOri:false},motionOn:false,runMode:()=> 'measure',SES:{addEvent(){}},Date});vm.runInContext(loggerCode+';globalThis.logger=L',data);data.logger.add({audio:null,vib:null,motion:null,tilt:null,heading:null,emf:.8,dist:4,mood:'angry'});const row=data.logger.rows[0];assert.equal(row.length,21);assert.equal(row[2],'measure');assert(row.slice(4,20).every(v=>v===null));data.ui.measure=false;data.logger.add({audio:null,vib:null,motion:null,tilt:null,heading:null,emf:.8,dist:4,mood:'angry'});assert.equal(data.logger.rows[1][19],'angry');
assert(html.includes('await SES.save(true); setMeasure(on)'));assert(html.includes('logAcc >= .1 && !SES.saving'));assert(script.indexOf('const snapshot =')<script.indexOf('const audioBlob = await this.stopAudio()'));assert(html.includes('if (!ui.measure && pose.op > .02)'));
const app=readFileSync('dist/app.mjs','utf8');const els=new Map(),$=id=>{if(!els.has(id))els.set(id,{});return els.get(id)};let n=0,revoked=[];const playback=vm.createContext({local:{clipUrl:null,clip:null},URL:{createObjectURL:()=> 'blob:'+ ++n,revokeObjectURL:u=>revoked.push(u)},$,download(){},Date});vm.runInContext(app.slice(app.indexOf('function showLocalClip(')),playback);const a={type:'audio/webm'},b={type:'audio/mp4'};playback.showLocalClip(a);assert.equal($('localPlayback').src,'blob:1');playback.showLocalClip(b);assert.deepEqual(revoked,['blob:1']);assert.equal(playback.local.clip,b);assert.equal($('localClip').hidden,false);assert(app.includes('(state.session.soundEvents??=[]).push(entry)'));
console.log('PASS: measurement/demo capture provenance, null CSV sensors and fictional fields, mode switching guard, save snapshot, audio playback/replacement and structured sound journal.');
