import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {translate,EN,initLanguage} from './dist/i18n.mjs';
assert.equal(translate('Камер асаах','en'),'Enable camera');assert.equal(translate('Камер асаах','mn'),'Камер асаах');assert.equal(translate('АРЫН КАМЕР · 1280 × 720','en'),'REAR CAMERA · 1280 × 720');assert.equal(translate('Actual transcript / Сайн байна уу','en'),'Actual transcript / Сайн байна уу');assert.equal(translate('  Хаах  ','en'),'  Close  ');assert.equal(translate('Сонсож байна · 8 сек үлдлээ','en'),'Recording · 8 seconds remaining');assert(Object.keys(EN).length>100);
const fakeElement=()=>({nodeType:1,childNodes:[],hasAttribute(){return false},value:'',onclick:null,onchange:null,hidden:true,open:false,focus(){},showModal(){this.open=true},close(){this.open=false},classList:{add(){}}});const nodes=new Map(['appLang','languageDialog','chooseMn','chooseEn','chooseEs','chooseId','chooseJa'].map(k=>[k,fakeElement()]));let stored=null;globalThis.document={getElementById:id=>nodes.get(id),documentElement:{},body:fakeElement()};globalThis.localStorage={getItem:()=>stored,setItem:(_,v)=>stored=v};globalThis.MutationObserver=class{observe(){}};
let ui=initLanguage();assert(nodes.get('languageDialog').open);nodes.get('chooseEn').onclick();assert.equal(ui.getLanguage(),'en');assert.equal(document.documentElement.lang,'en');assert.equal(stored,'en');assert.equal(nodes.get('languageDialog').open,false);nodes.get('languageDialog').open=false;ui=initLanguage();assert.equal(ui.getLanguage(),'en');assert.equal(nodes.get('languageDialog').open,false);nodes.get('appLang').value='mn';nodes.get('appLang').onchange();assert.equal(stored,'mn');globalThis.localStorage={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}};ui=initLanguage();nodes.get('chooseEn').onclick();assert.equal(ui.getLanguage(),'en');
for(const name of ['index.html','lab.html']){const html=readFileSync('dist/'+name,'utf8');for(const id of nodes.keys())assert(html.includes('id="'+id+'"'));assert(html.includes('viewport-fit=cover'))}const css=readFileSync('dist/style.css','utf8');assert(css.includes('min-height:44px'));assert(css.includes('max-width:1100px'));assert(css.includes('safe-area-inset-bottom'));assert(css.includes('blueprint-ghost.webp'));assert(existsSync('dist/blueprint-ghost.webp'));
console.log('PASS: MN/EN text and original transcripts, first launch selection, language persistence/switch/storage failure, language DOM, mobile/tablet CSS and blueprint asset. Physical layout untested.');

for(const [language,button] of [['mn','chooseMn'],['en','chooseEn'],['es','chooseEs'],['id','chooseId'],['ja','chooseJa']]){stored=null;globalThis.localStorage={getItem:()=>stored,setItem:(_,v)=>stored=v};ui=initLanguage();nodes.get(button).onclick();assert.equal(ui.getLanguage(),language);assert.equal(stored,language);ui=initLanguage();assert.equal(ui.getLanguage(),language);for(const [mn,en]of Object.entries(EN)){assert(translate(mn,language).trim());if(!['mn','en'].includes(language))assert.notEqual(translate(mn,language),en);}if(!['mn','en'].includes(language))assert.notEqual(translate('Сонсож байна · 8 сек үлдлээ',language),'Recording · 8 seconds remaining');}
console.log('PASS: five-language catalog, first launch choice, persistence/reload and dynamic countdown');
